<style>
    .container{
        border: 1px solid #e6e6e6;
    }
</style>
<div id="jobs">
    <?php
    foreach ($jobs as $job){ ?>
        <div id="job">
            <div id="title"><h2><?=$job['_source']['title'];?></h2></div>
            <div id="description"><?=$job['_source']['description'];?></div>
            <div id="salario"><b>Salario:</b>R$ <?=number_format($job['_source']['salario'], 2, ',', '.');?></div>
            <div id="cidade"><b>Cidade:</b> <?php foreach ($job['_source']['cidadeFormated'] as $cidade){ echo $cidade."<br>"; }?></div>
        </div>
        <hr>
    <?php } ?>
</div>
